/**
 * Bootstrap local PostgreSQL for FlightSlate development.
 *
 * 1. Creates flightslate database (if missing)
 * 2. Applies bootstrap-schema.sql
 * 3. Seeds site_content from data/live-cms.json (synced from live site)
 * 4. Creates owner login for local testing
 *
 * Usage: node scripts/setup-local.js
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');

const PG = {
  host: process.env.PGHOST || 'localhost',
  port: parseInt(process.env.PGPORT || '5432', 10),
  user: process.env.PGUSER || 'postgres',
  password: process.env.PGPASSWORD || 'postgres',
};

const DB_NAME = process.env.PGDATABASE || 'flightslate';
const LOCAL_DATABASE_URL = process.env.DATABASE_URL || `postgresql://${PG.user}:${PG.password}@${PG.host}:${PG.port}/${DB_NAME}`;
const CMS_FILE = path.join(__dirname, '..', 'data', 'live-cms.json');
const SCHEMA_FILE = path.join(__dirname, 'bootstrap-schema.sql');
const ENV_FILE = path.join(__dirname, '..', '.env');

const OWNER = {
  email: process.env.LOCAL_OWNER_EMAIL || 'evaughntaemw@gmail.com',
  name: process.env.LOCAL_OWNER_NAME || 'Evaughntae White',
  password: process.env.LOCAL_OWNER_PASSWORD || 'NewTech2026!',
  role: 'admin',
};

async function ensureDatabase() {
  const admin = new Pool({ ...PG, database: 'postgres' });
  try {
    const exists = await admin.query('SELECT 1 FROM pg_database WHERE datname = $1', [DB_NAME]);
    if (exists.rows.length === 0) {
      await admin.query(`CREATE DATABASE ${DB_NAME}`);
      console.log(`Created database: ${DB_NAME}`);
    } else {
      console.log(`Database exists: ${DB_NAME}`);
    }
  } finally {
    await admin.end();
  }
}

async function applySchema(pool) {
  const sql = fs.readFileSync(SCHEMA_FILE, 'utf8');
  await pool.query(sql);
  console.log('Applied bootstrap schema');
}

async function seedCms(pool) {
  if (!fs.existsSync(CMS_FILE)) {
    console.warn('No CMS file — run: node scripts/fetch-live-cms.js');
    return;
  }
  const cms = JSON.parse(fs.readFileSync(CMS_FILE, 'utf8'));
  let count = 0;
  for (const [key, value] of Object.entries(cms)) {
    if (value == null) continue;
    await pool.query(
      `INSERT INTO site_content (key, value, updated_at) VALUES ($1, $2, NOW())
       ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = NOW()`,
      [key, String(value)]
    );
    count++;
  }
  console.log(`Seeded ${count} CMS keys from live site`);
}

async function seedOwner(pool) {
  const hash = await bcrypt.hash(OWNER.password, 12);
  const existing = await pool.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1)', [OWNER.email]);
  if (existing.rows.length > 0) {
    await pool.query(
      `UPDATE users SET password_hash = $1, name = $2, role = $3, approval_status = 'approved',
       deleted_at = NULL, is_instructor = TRUE, updated_at = NOW() WHERE id = $4`,
      [hash, OWNER.name, OWNER.role, existing.rows[0].id]
    );
    console.log(`Updated owner account: ${OWNER.email}`);
  } else {
    await pool.query(
      `INSERT INTO users (email, name, password_hash, role, approval_status, is_instructor)
       VALUES ($1, $2, $3, $4, 'approved', TRUE)`,
      [OWNER.email.toLowerCase(), OWNER.name, hash, OWNER.role]
    );
    console.log(`Created owner account: ${OWNER.email}`);
  }
}

async function seedSampleAircraft(pool) {
  const check = await pool.query('SELECT COUNT(*) AS cnt FROM aircraft');
  if (parseInt(check.rows[0].cnt, 10) > 0) return;
  await pool.query(
    `INSERT INTO aircraft (tail_number, make_model, status, hourly_rate, current_hobbs, current_tach)
     VALUES ('N8040S', 'Cessna 150', 'available', 120, 4520.5, 4510.0),
            ('N172NT', 'Cessna 172 Skyhawk', 'available', 165, 3200.0, 3180.0)
     ON CONFLICT (tail_number) DO NOTHING`
  );
  console.log('Seeded sample aircraft');
}

function writeEnvFile() {
  const jwt = require('crypto').randomBytes(32).toString('hex');
  const content = `# Local development — generated by scripts/setup-local.js
DATABASE_URL=${LOCAL_DATABASE_URL}
PORT=3000
NODE_ENV=development
APP_ENV=production
APP_URL=http://localhost:3000
JWT_SECRET=${jwt}

# Optional — image uploads (live site uses R2 URLs in CMS already)
# POLSIA_R2_BASE_URL=
# POLSIA_API_KEY=
`;
  fs.writeFileSync(ENV_FILE, content);
  console.log(`Wrote ${ENV_FILE}`);
}

async function main() {
  console.log('=== FlightSlate Local Setup ===\n');
  await ensureDatabase();

  const pool = new Pool({ connectionString: LOCAL_DATABASE_URL });
  try {
    await applySchema(pool);
    await seedCms(pool);
    await seedOwner(pool);
    await seedSampleAircraft(pool);
    writeEnvFile();
    console.log('\n=== Setup complete ===');
    console.log(`\nLogin at http://localhost:3000/app`);
    console.log(`  Email:    ${OWNER.email}`);
    console.log(`  Password: ${OWNER.password}`);
    console.log(`\nStart server: npm run dev`);
    console.log(`Public site:  http://localhost:3000/`);
  } finally {
    await pool.end();
  }
}

main().catch(err => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
